### ISSUE TITLE
problem running on mac os x 11.4

### ISSUE THREAD

**Issue by rhaynes74** [getreu/tp-note#3]
Hi folks, downloading the mac binary and running ./tp-note yields

*** ERROR: Unable to load, parse or write the configuration file:
---
Bad TOML data: missing field `debug_arg_default` at line 1 column 1

Note: this error may occur after upgrading Tp-Note due
to some incompatible configuration file changes.

For now, Tp-Note backs up the existing configuration
file and next time it starts, it will create a new one
with default values.
*** ERROR: Can not backup and delete the erroneous configuration file:
---
Configuration file not found.

Rerunning doesn't fix it.  There is no config file in ~/.config/tp-note/

I tried to trick it by doing a 

touch ~/.config/tp-note/tp-note.toml

and then rerunning, but unfortunately no dice.

**Comment by getreu** [comment]
"*Unable to load, parse or write the configuration file*" usually means that *Tp-Note* finds an outdated version, which is not compatible with the *Tp-Note* binary you are using. What prints `tp-note --version`? 
"*Can not backup and delete the erroneous configuration file*" probably means that *Tp-Note* lacks write permission in the directory where it wants to store/back up its configuration file.
Please check in the error message, below "Additional technical details" in the last line it says `* configuration file: ...` which indicates the location of the configuration file. Delete this file by hand, check the directory's write permission and restart *Tp-Note*.

**Comment by rhaynes74** [comment]
Thanks for the reply - the rest of the message said:

*** ERROR: Can not backup and delete the erroneous configuration file:
---
Configuration file not found.

Please do it manually.
fatal runtime error: Rust cannot catch foreign exceptions

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by getreu** [comment]
Ok, I see.

When *Tp-Note* starts, it checks if there is a configuration file and if not it tries to create one in some default location.
I your case, it seems that at this location there is already some configuration file already from a previous version of *Tp-Note*: `Bad TOML data: missing field debug_arg_default at line 1 column 1`
As this file is incompatible, *Tp-Note* tries to get it out of the way by renaming it. This failed: `Can not backup and delete the erroneous configuration file`.

You need to:
1. Find out where *Tp-Note* tries to read its configuration file `tp-note.toml`.
2. Delete this file manually.

Concerning 1.: Unfortunately, at the moment, *Tp-Note* can not reliably determine this location, because of [Expose config path · Issue #33 · rust-cli/confy](https://github.com/rust-cli/confy/issues/33). When you run `tp-note --popup`, the last line of the error popup shows its "best guess" of the location of the configuration file, but still it can be located somewhere else. I suggest searching for your configuration file `tp-note.toml` with some file utility ` and then manually delete it. Once this file is deleted, restart *Tp-Note*. It should silently create a new configuration file and operate correctly.

Please tell me how it goes.

# Workaround

If the above does not help, you can always instruct *Tp-Note* to use some alternative configuration file with the command line option `--config`. For example:

    tp-note --config ~/tp-note.toml

or just:

    tp-note --config tp-note.toml

**Comment by rhaynes74** [comment]
Thanks - I was able to get things up and running with the workaround.  Looking forward to playing around a little.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment]
Hi folks, now that I am up and running - are there particulars pieces of the config file that I should pay attention to or typically need to be modified to adjust workflows?

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by getreu** [comment]
Good to hear. I am working on bugfix for this issue, I let you know.

> are there particulars pieces of the config file that I should pay attention to or typically need to be modified to adjust workflows?

Good start is :
* [TP-NOTE(1) Version 1.12.19 | Tp-Note customization](https://blog.getreu.net/projects/tp-note/tp-note--manpage.html#customization) and
* [tp_note::config - Rust](https://blog.getreu.net/projects/tp-note/_downloads/doc/tp_note/config/index.html#constants)

**Comment by getreu** [comment]
#3 should be solved with commit: f6ca6dcbccde1c742b6b2805a1ea29d355444910 which is included in v1.13.0.

Could you download and install [tp-note-v1.13.0-x86\_64-apple-darwin.tar.gz](https://github.com/getreu/tp-note/releases/download/v1.13.0/tp-note-v1.13.0-x86_64-apple-darwin.tar.gz) ?

The above error messages should not show up any more. If everything goes well, you will just see a popup message informing that the config file was upgraded to v1.13.0.

Can you confirm?

**Comment by rhaynes74** [comment]
Hi - thanks, I will try this with the next update.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
